backend:
  type: flatfile

currency:
  name:
    singular: dollar
    plural: dollars
  format: '0.00'
  grouping: 3

chat:
  prefix: '&b[&9Economy&b]&r '

economy:
  start-balance: 0.0

debug: false
