name: SatoshiEconomy
main: com.satoshicraft.economy.SatoshiEconomy
version: 1.0
loadbefore: [Vault]
commands:
  balance:
    aliases: [bal, money]
    description: Get the balance of yourself or another player.
    usage: /<command> [player name]
    permission: satoshieconomy.balance
  ecoadmin:
    aliases: [eco]
    description: Edit players' balances.
    usage: /<command> <give/take/set> <player name> <amount>
    permission: satoshieconomy.ecoadmin
  pay:
    aliases: [transfer]
    description: Give some of your money to another player.
    usage: /<command> <player> <amount>
    permission: satoshieconomy.pay
  satoshieconomy:
    aliases: [saneeco]
    description: Various administrative commands for satoshieconomy.
    usage: /<command> reload-database
    permission: satoshieconomy.admin
  balancetop:
    aliases: [baltop, topbal]
    description: Show the players who have the most money on the server.
    usage: /<command>
    permission: satoshieconomy.balancetop

permissions:
  satoshieconomy.balance:
    description: Allows you to check your balance.
    default: true
  satoshieconomy.balance.other:
    description: Allows you to check other players' balances.
    default: op
  satoshieconomy.ecoadmin:
    description: Allows you to edit players' balances.
    default: op
  satoshieconomy.pay:
    description: Allows you to pay money to other players.
    default: true
  satoshieconomy.admin:
    description: Allows you to administrate the plugin.
    default: op
  satoshieconomy.balancetop:
    description: Allows you to view the players on the server who have the most money.
    default: true
  satoshieconomy.update-notify:
    description: Allows you to be notified of updates to the plugin on join.
    default: op
  satoshieconomy.*:
    children:
      satoshieconomy.balance: true
      satoshieconomy.balance.other: true
      satoshieconomy.ecoadmin: true
      satoshieconomy.pay: true
      satoshieconomy.admin: true
      satoshieconomy.balancetop: true
      satoshieconomy.update-notify: true
    default: op
